### ISSUE TITLE
Cannot find installer puppet-enterprise-3.8.7-el-6-x86_64.tar.gz

### ISSUE THREAD

**Issue by wernerbahlke** [Sharpie/puppet-debugging-kit#16]
Hi,

I am trying to get the puppet-debugging kit going to test upgrade to Puppet 4. On a Mac I installed both Virtual box and Vagrant. But when running

vagrant up pe-387-masterI get this error:

==> pe-387-master: Running provisioner: pe_bootstrap...
Cannot fetch installer puppet-enterprise-3.8.7-el-6-x86_64.tar.gz; no download source available.

Installers available for use:
The Puppet Enterprise installer puppet-enterprise-3.8.7-el-6-x86_64.tar.gz
is not available. Please set the `download_root` config option to a valid
mirror, or add the installer yourself by using the `vagrant pe-build copy`
command. Downloads for Puppet Enterprise are available for download at
https://puppetlabs.com/puppet/puppet-enterprise/

**Comment by Sharpie** [comment]
As noted by the error message, installers must be downloaded from https://puppetlabs.com/puppet/puppet-enterprise/ and added to the Vagrant installation using `vagrant pe-build copy`.
